export function animal(): string {
    const index = Math.floor(Math.random() * animals.length);
    return animals[index];
}

const animals = [
    "Common ostrich",
    "Helmeted guineafowl",
    "Wild turkey",
    "Southern screamer",
    "Black-necked swan",
    "Mute swan",
    "Marbled teal",
    "African pygmy goose",
    "Ruddy duck",
    "American flamingo",
    "Nicobar pigeon",
    "Pied imperial pigeon",
    "Victoria crowned pigeon",
    "Pheasant pigeon",
    "Black-naped fruit-dove",
    "Beautiful fruit dove",
    "Jambu fruit-dove",
    "White-throated ground-dove",
    "Tawny frogmouth",
    "Lady Ross’ turaco",
    "Roadrunner",
    "Kori bustard",
    "Buff-crested bustard",
    "Sunbittern",
    "Black crowned-crane",
    "White-naped crane",
    "Sandhill crane",
    "Red-crowned crane",
    "Blue crane",
    "Wood stork",
    "Roseate spoonbill",
    "Cape thick-knee",
    "Masked lapwing",
    "Common barn owl",
    "Eurasian eagle owl",
    "Great horned owl",
    "Eastern screech owl",
    "Spectacled owl",
    "Barred owl",
    "Black vulture",
    "Cinereous vulture",
    "Golden eagle",
    "Red-tailed hawk",
    "Red-shouldered hawk",
    "Harris’ hawk",
    "Secretary bird",
    "Speckled mousebird",
    "Red-billed hornbill",
    "Southern ground hornbill",
    "Green woodhoopoe",
    "Blue-bellied roller",
    "Laughing kookaburra",
    "Blue-crowned motmot",
    "Green aracari",
    "Coconut lorikeet",
    "Australian rainbow lorikeet",
    "Forsten’s lorikeet",
    "Marigold lorikeet",
    "Vasa parrot",
    "Sulphur-crested cockatoo",
    "Blue-faced honeyeater",
    "Plush-crested jay",
    "White-crested laughing thrush",
    "Violet-backed starling",
    "Emerald starling",
    "Snowy-headed robin chat",
    "Red-billed leiothrix",
    "White-headed buffalo weaver",
    "Taveta golden weaver",
    "Red-crested cardinal",
    "Black-billed magpie",
    "Buff Orpington chicken",
    "Russian Orloff chicken",
    "Hamburg chicken",
    "Serama chicken",
    "Old English Bantam chicken",
    "red-crested turaco",
    "Madagascar hissing cockroach",
    "Honeybee",
    "Bony fish",
    "Rainbow Sharkminnow",
    "Bristlenose catfish",
    "Lionfish",
    "Komodo Dragon",
    "Alligator snapping turtle",
    "Box turtle",
    "Eastern box turtle",
    "Coahuila box turtle",
    "Black-nobbed map turtle",
    "Diamondback terrapin",
    "Radiated tortoise",
    "Aldabra giant tortoise",
    "Desert tortoise",
    "Gopher tortoise",
    "Home’s hinge back tortoise",
    "African pancake tortoise",
    "Egyptian tortoise",
    "Chinese three-striped box turtle",
    "Japanese pond turtle",
    "Philippine sail-finned lizard",
    "San Esteban Island chuckwalla",
    "New Caledonia giant gecko",
    "Prehensile-tailed skink",
    "Blue-tongued skink",
    "Caiman lizard",
    "Mexican beaded lizard",
    "Woma",
    "Royal/ball python",
    "Boa constrictor",
    "Emerald tree boa",
    "Garden tree boa",
    "Eastern indigo snake",
    "Cave snake",
    "Red-tailed ratsnake",
    "Milksnake",
    "Corn snake",
    "Western ratsnake",
    "Copperhead",
    "Cottonmouth",
    "Timber rattlesnake",
    "American alligator",
    "Blood Python",
    "Shingleback Skink",
    "Asian giant toad",
    "Cane toad",
    "yellow-headed poison frog",
    "White’s tree frog",
    "Eastern Bongo",
    "Virginia opossum",
    "Lesser Madagascar hedgehog tenrec",
    "African elephant",
    "Southern three-banded armadillo",
    "Hoffmann’s two-toed sloth",
    "Giant anteater",
    "Crowned lemur",
    "Ring-tailed lemur",
    "Cotton-top tamarin",
    "Common squirrel monkey",
    "Black howler",
    "Black-handed spider monkey",
    "De Brazza’s monkey",
    "Lar gibbon",
    "Sumatran orangutan",
    "Prevost’s squirrel",
    "Woodchuck",
    "Naked mole-rat",
    "Cape porcupine",
    "Sand cat",
    "Black-footed cat",
    "Serval",
    "Bobcat",
    "Pallas’s cat",
    "Lion",
    "Jaguar",
    "Coyote",
    "Fennec fox",
    "North American black bear",
    "North American river otter",
    "Giant otter",
    "Ferret",
    "Striped skunk",
    "Red panda",
    "Plains zebra",
    "Giraffe",
    "Red-flanked duiker",
    "Blue duiker",
    "Chinchilla",
    "Miniature Donkey",
    "Dwarf Nigerian goat",
    "Gulf Coast sheep",
    "Blackbelly sheep",
    "Brown rat",
    "Eastern black rhinoceros",
    "Brown-nosed Coati",
    "Bettong",
];
